# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a99a56805d1d3bc1442fca642bf29c3c59e8b6d63e9ef1e1fc39998215dad04bf64763d5e5885380cc61fd4c276b3eb466686201c09de9a8e47bfdbdfc8f3c75

test:
  secret_key_base: dfed467cf7977085b01983cc0bd24295e919f7ae8f846ab1d3e54661ac1b0d17ea0f4cc6dec71aba2f824c1f2bf692e41491c55570068618ee222c581f4c087d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
